// Package prepare reads private deployment data generated by scripts/prepare.sh.
package prepare

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"
)

const DefaultPath = ".prepare/marvis.json"

const maxFileSize = 64 << 10

var qimeiPattern = regexp.MustCompile(`^[0-9a-fA-F]{36}$`)

type Data struct {
	AccessKey string `json:"access_key"`
	QIMEI36   string `json:"qimei36"`
}

// Load validates the whole file. Errors never include credential values or JSON.
func Load(path string) (Data, error) {
	f, err := os.Open(path)
	if err != nil {
		return Data{}, fmt.Errorf("读取 prepare 文件: %w", err)
	}
	defer f.Close()
	raw, err := io.ReadAll(io.LimitReader(f, maxFileSize+1))
	if err != nil {
		return Data{}, fmt.Errorf("读取 prepare 文件: %w", err)
	}
	if len(raw) > maxFileSize {
		return Data{}, fmt.Errorf("prepare 文件不能超过 64 KiB")
	}
	var data Data
	if err := json.Unmarshal(raw, &data); err != nil {
		return Data{}, fmt.Errorf("prepare 文件不是有效的 JSON 对象")
	}
	data.AccessKey = strings.TrimSpace(data.AccessKey)
	data.QIMEI36 = strings.ToLower(strings.TrimSpace(data.QIMEI36))
	if data.AccessKey == "" || len(data.AccessKey) > 256 || strings.IndexFunc(data.AccessKey, func(r rune) bool { return r < 33 || r > 126 }) >= 0 {
		return Data{}, fmt.Errorf("prepare 文件缺少有效的 access_key")
	}
	if !qimeiPattern.MatchString(data.QIMEI36) {
		return Data{}, fmt.Errorf("prepare 文件的 qimei36 必须是已注册的 36 位十六进制设备号")
	}
	return data, nil
}
